name: create automatic PR

on:
  push:
    branches:
      - main

jobs:
  generate_pr:
    name: generate pr for main branch
    runs-on: self-hosted

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: make changes to file
      run: |
        echo "Hello, GitHub Actions!" > hello.txt
      
    - name: Commit all changed files back to the repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update hello.txt"
        commit_options: "--no-verify --signoff"
        repository: .
        branch: "feature/test-1"
        create_branch: true
        commit_author: vishalkumar-activelabs <vishal.kumar@cloudactivelabs.com>
        commit_user_email: vishal.kumar@cloudactivelabs.com
        commit_user_name: vishalkumar-activelabs

