name: create automatic PR

on:
  push:
    branches:
      - main

jobs:
  generate_pr:
    name: generate pr for main branch
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: make changes to file
      run: |
        echo "Hello, GitHub Actions!" > hello.txt
      
    - name: commit and push changes
      run: |
        git config --global user.email "vishal.kumar@cloudactivelabs.com"
        git config --global user.name "vishalkumar-activelabs"
        git add -A
        git commit -m "update from github actions"
        git push

