name: create automatic PR

on:
  push:
    branches:
      - main

jobs:
  generate_pr:
    name: generate pr for main branch
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Modify files in auto-pr-branch
    - name: Make changes in auto-pr-branch
      run: |
        git checkout -b auto-pr-branch origin/auto-pr-branch
        # Make changes to files
        echo "Updated content" >> example.txt
        git add example.txt
        git commit -m "Update example.txt"
        git push origin auto-pr-branch

    - name: Set commit author name as an environment variable
      id: commit_info
      run: |
        $COMMIT_AUTHOR = git log -1 --pretty=format:'%an'
        Write-Host "GIT_COMMIT_AUTHOR_NAME=$COMMIT_AUTHOR" >> $env:GITHUB_ENV
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "auto-pr-branch"
        base: "main"
        title: Automatic PR from main
        body: |
          This is an automatic PR created from changes in the main branch by ${{ env.GIT_COMMIT_AUTHOR_NAME }}.
          # Additional options can be specified here, like reviewers, labels, etc.
