name: Build and Deploy to Local Registry

on:
  push:
    branches:
      - dev-test
  workflow_dispatch:
    branches:
      - dev-test

jobs:
  build_and_run_project_1:
    name: Build and Run Project 1
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=5006"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 5006 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 5006"
        }

    - name: Build Docker for Project 1
      run: |
        cd project1
        docker build -t nodejs-crud-dev-release-project-1 .

    - name: Run Docker for Project 1
      run: |
        cd project1
        docker run -dp 5006:5001 --name dev-release-project-1 nodejs-crud-dev-release-project-1
