name: Manual-Actions-Workflow-development-release

on:
  workflow_dispatch

jobs:
  build_and_run_project_1:
    name: Build and Run Project 1
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=5006"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 5006 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 5006"
        }

    - name: Build and run Docker for Project 1
      run: |
        cd project1
        $project1Version = (Get-Content package.json | ConvertFrom-Json).version
        docker build -t nodejs-crud-dev-release-project-1:dev-rel-$project1Version .
        docker run -dp 5006:5001 --name dev-release-project-1 nodejs-crud-dev-release-project-1:dev-rel-$project1Version

  build_and_run_project_2:
    name: Build and Run Project 2
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=4006"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 4006 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 4006"
        }

    - name: Build and run Docker for Project 2
      run: |
        cd project2
        $project2Version = (Get-Content package.json | ConvertFrom-Json).version
        docker build -t nodejs-crud-dev-release-project-2:dev-rel-$project2Version .
        docker run -dp 4006:4001 --name dev-release-project-2 nodejs-crud-dev-release-project-2:dev-rel-$project2Version
