name: Build and Deploy to Local Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image to local registry
      env:
        DOCKER_REGISTRY: localhost:5000
        IMAGE_NAME: nodejs-crud
        TAG: latest
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build -t $DOCKER_REGISTRY/$IMAGE_NAME:$TAG --platform linux/amd64,linux/arm64 .
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:$TAG
