name: Build and Deploy to Local Registry

on:
  push:
    branches:
      - main

jobs:
  build_and_run_project_1:
    name: Build and Run Project 1
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker for Project 1
      run: |
        cd project1
        docker build -t nodejs-crud-project-1 .
        docker run -dp 5001:5001 nodejs-crud-project-1

  # build_and_run_project_2:
  #   name: Build and Run Project 2
  #   runs-on: self-hosted

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Build and run Docker for Project 2
  #     run: |
  #       cd project2
  #       docker build -t nodejs-crud-project-2 .
  #       docker run -dp 4001:4001 nodejs-crud-project-2
