name: Build and Deploy to Local Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: List local Docker images
      run: docker images
    
    - name: List local Docker container
      run: docker ps

    - name: Login to Docker Registry
      run: docker login -u myusername -p mypassword localhost:5001

    - name: List local Docker images
      run: docker images

    - name: Build and push Docker image to local registry
      env:
        DOCKER_REGISTRY: localhost:5001
        IMAGE_NAME: register
        TAG: 2
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build -t $DOCKER_REGISTRY/$IMAGE_NAME:$TAG --platform linux/amd64,linux/arm64 .
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:$TAG
