name: Manual-Actions-Workflow-production-release

on:
  workflow_dispatch

jobs:
  build_and_run_project_1:
    name: Build and Run Project 1
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=5002"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 5002 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 5002"
        }

    - name: Build and run Docker for Project 1
      run: |
        cd project1
        docker build -t nodejs-crud-prod-releaseproject-1 .
        docker run -dp 5002:5001 --name prod-release-project-1 nodejs-crud-prod-releaseproject-1

  build_and_run_project_2:
    name: Build and Run Project 2
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=4002"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 4002 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 4002"
        }

    - name: Build and run Docker for Project 2
      run: |
        cd project2
        docker build -t nodejs-crud-prod-releaseproject-2 .
        docker run -dp 4002:4001 --name prod-release-project-2 nodejs-crud-prod-releaseproject-2
