name: Build and Deploy to Local Registry

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_run_project_1:
    name: Build and Run Project 1
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=5002"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 5002 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 5002"
        }

    - name: Build and run Docker for Project 1
      run: |
        cd project1
        docker build -t nodejs-crud-project-1 .
        docker run -dp 5002:5002 --name production-release nodejs-crud-project-1

  build_and_run_project_2:
    name: Build and Run Project 2
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=4002"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 4002 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 4002"
        }

    - name: Build and run Docker for Project 2
      run: |
        cd project2
        docker build -t nodejs-crud-project-2 .
        docker run -dp 4002:4002 --name production-release nodejs-crud-project-2
