name: Build and Deploy production

on:
  push:
    branches:
      - main

jobs:
  login-to-docker-registry:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: http://localhost:5000  # Replace with your local registry URL
          username: ${{ secrets.REGISTRY_USERNAME }}  # Replace with your registry username
          password: ${{ secrets.REGISTRY_PASSWORD }}  # Replace with your registry password or token

  # build_and_run_project_1:
  #   name: Build and Run Project 1
  #   runs-on: self-hosted

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Check running containers on port
  #     run: |
  #       $CONTAINER_ID = docker ps -q --filter "publish=5001"
  #       if ($CONTAINER_ID) {
  #         Write-Output "Found container running on port 5001 with ID: $CONTAINER_ID"
  #         docker rm -f $CONTAINER_ID
  #       }
  #       else {
  #         Write-Output "No container found running on port 5001"
  #       }

  #   - name: Build and run Docker for Project 1
  #     run: |
  #       cd project1
  #       $project1Version = (Get-Content package.json | ConvertFrom-Json).version
  #       docker build -t nodejs-crud-prod-project-1:prod-$project1Version .
  #       docker run -dp 5001:5001 --name prod-project-1 nodejs-crud-prod-project-1:prod-$project1Version

  # build_and_run_project_2:
  #   name: Build and Run Project 2
  #   runs-on: self-hosted

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Check running containers on port
  #     run: |
  #       $CONTAINER_ID = docker ps -q --filter "publish=4001"
  #       if ($CONTAINER_ID) {
  #         Write-Output "Found container running on port 4001 with ID: $CONTAINER_ID"
  #         docker rm -f $CONTAINER_ID
  #       }
  #       else {
  #         Write-Output "No container found running on port 4001"
  #       }

  #   - name: Build and run Docker for Project 2
  #     run: |
  #       cd project2
  #       $project2Version = (Get-Content package.json | ConvertFrom-Json).version
  #       docker build -t nodejs-crud-prod-project-2:prod-$project2Version .
  #       docker run -dp 4001:4001 --name prod-project-2 nodejs-crud-prod-project-2:prod-$project2Version
