name: Build and Deploy stagging

on:
  push:
    branches:
      - stag

jobs:
  build_and_run_project_1:
    name: Build and Run Project 1
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=5003"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 5003 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 5003"
        }

    - name: Build and run Docker for Project 1
      run: |
        docker login --username vishalkumar-activelabs --password ${{ secrets.DOCKER_REGISTRY_TOKEN }} ghcr.io
        cd project1
        $project1Version = (Get-Content package.json | ConvertFrom-Json).version
        # docker build -t nodejs-crud-stag-project-1:stag-$project1Version .
        # docker run -dp 5003:5001 --name stag-project-1 nodejs-crud-stag-project-1:stag-$project1Version
        docker build -t ghcr.io/vishalkumar-activelabs/nodejs-crud-stag-project-1:stag-$project1Version .
        docker push ghcr.io/vishalkumar-activelabs/nodejs-crud-stag-project-1:stag-$project1Version

  build_and_run_project_2:
    name: Build and Run Project 2
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=4003"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 4003 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 4003"
        }

    - name: Build and run Docker for Project 2
      run: |
        docker login --username vishalkumar-activelabs --password ${{ secrets.DOCKER_REGISTRY_TOKEN }} ghcr.io
        cd project2
        $project2Version = (Get-Content package.json | ConvertFrom-Json).version
        # docker build -t nodejs-crud-stag-project-2:stag-$project2Version .
        # docker run -dp 4003:4001 --name stag-project-2 nodejs-crud-stag-project-2:stag-$project2Version
        docker build -t ghcr.io/vishalkumar-activelabs/nodejs-crud-stag-project-2:stag-$project2Version .
        docker push ghcr.io/vishalkumar-activelabs/nodejs-crud-stag-project-2:stag-$project2Version
