name: Build and Deploy to Local Registry

on:
  push:
    branches:
      - stag

jobs:
  build_and_run_project_1:
    name: Build and Run Project 1
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=5003"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 5003 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 5003"
        }

    - name: Build and run Docker for Project 1
      run: |
        cd project1
        docker build -t nodejs-crud-project-1 .
        docker run -dp 5003:5003 --name stag-project-1 nodejs-crud-project-1

  build_and_run_project_2:
    name: Build and Run Project 2
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check running containers on port
      run: |
        $CONTAINER_ID = docker ps -q --filter "publish=4003"
        if ($CONTAINER_ID) {
          Write-Output "Found container running on port 4003 with ID: $CONTAINER_ID"
          docker rm -f $CONTAINER_ID
        }
        else {
          Write-Output "No container found running on port 4003"
        }

    - name: Build and run Docker for Project 2
      run: |
        cd project2
        docker build -t nodejs-crud-project-2 .
        docker run -dp 4003:4003 --name stag-project-2 nodejs-crud-project-2
